import { describe, expect, it } from 'vitest';

import type { UiKitConfiguration } from '@openzeppelin/transaction-form-types';

import { generateRainbowKitExportables } from '../export-service';

describe('RainbowKit Export Service', () => {
  describe('generateRainbowKitExportables', () => {
    it('should generate a valid RainbowKit config file with all properties', () => {
      // Arrange
      const uiKitConfig: UiKitConfiguration = {
        kitName: 'rainbowkit',
        kitConfig: {
          appName: 'My Test dApp',
          learnMoreUrl: 'https://test-dapp.com',
          // Note: other properties like 'projectId' are handled by the generator
        },
      };

      const expectedFilePath = 'src/config/wallet/rainbowkit.config.ts';

      // Act
      const result = generateRainbowKitExportables(uiKitConfig);
      const generatedCode = result[expectedFilePath];

      // Assert
      expect(result).toHaveProperty(expectedFilePath);
      expect(generatedCode).toContain('// Generated by the OpenZeppelin Transaction Form Builder');

      // Check for wagmiParams content, accounting for JSON.stringify's double quotes on keys
      expect(generatedCode).toMatch(/"appName":\s*"My Test dApp"/);
      expect(generatedCode).toMatch(/"projectId":\s*"YOUR_PROJECT_ID"/);

      // Check for appInfo content
      expect(generatedCode).toMatch(/"learnMoreUrl":\s*"https:\/\/test-dapp\.com"/);
    });

    it('should generate a valid config with default learnMoreUrl when not provided', () => {
      // Arrange
      const uiKitConfig: UiKitConfiguration = {
        kitName: 'rainbowkit',
        kitConfig: {
          appName: 'Minimal dApp',
        },
      };
      const expectedFilePath = 'src/config/wallet/rainbowkit.config.ts';

      // Act
      const result = generateRainbowKitExportables(uiKitConfig);
      const generatedCode = result[expectedFilePath];

      // Assert
      expect(result).toHaveProperty(expectedFilePath);
      expect(generatedCode).toMatch(/"appName":\s*"Minimal dApp"/);

      // The generator provides a default value for learnMoreUrl
      expect(generatedCode).toMatch(/"learnMoreUrl":\s*"https:\/\/openzeppelin\.com"/);
    });
  });
});
