/**
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT IT MANUALLY.
 *
 * To update these versions, run the script:
 * pnpm update-export-versions
 */

export const packageVersions = {
  '@openzeppelin/ui-builder-adapter-evm': '0.13.0',
  '@openzeppelin/ui-builder-adapter-midnight': '0.13.0',
  '@openzeppelin/ui-builder-adapter-solana': '0.13.0',
  '@openzeppelin/ui-builder-adapter-stellar': '0.13.0',
  '@openzeppelin/ui-builder-react-core': '0.13.0',
  '@openzeppelin/ui-builder-renderer': '0.13.0',
  '@openzeppelin/ui-builder-storage': '0.13.0',
  '@openzeppelin/ui-builder-types': '0.13.0',
  '@openzeppelin/ui-builder-ui': '0.13.0',
  '@openzeppelin/ui-builder-utils': '0.13.0',
};
