/**
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT IT MANUALLY.
 *
 * To update these versions, run the script:
 * pnpm update-export-versions
 */

export const packageVersions = {
  '@openzeppelin/transaction-form-adapter-evm': '1.17.1',
  '@openzeppelin/transaction-form-adapter-midnight': '0.3.1',
  '@openzeppelin/transaction-form-adapter-solana': '0.3.0',
  '@openzeppelin/transaction-form-adapter-stellar': '0.3.0',
  '@openzeppelin/transaction-form-react-core': '1.17.0',
  '@openzeppelin/contracts-ui-builder-renderer': '1.17.1',
  '@openzeppelin/transaction-form-types': '1.17.0',
  '@openzeppelin/transaction-form-ui': '1.18.0',
  '@openzeppelin/transaction-form-utils': '1.17.0',
};
