/**
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT IT MANUALLY.
 *
 * To update these versions, run the script:
 * pnpm update-export-versions
 */

export const packageVersions = {
  '@openzeppelin/adapter-evm': '2.0.1',
  '@openzeppelin/adapter-midnight': '2.0.1',
  '@openzeppelin/adapter-polkadot': '2.0.0',
  '@openzeppelin/adapter-solana': '2.0.0',
  '@openzeppelin/adapter-stellar': '2.0.0',
  '@openzeppelin/ui-react': '3.0.0',
  '@openzeppelin/ui-renderer': '3.0.0',
  '@openzeppelin/ui-storage': '1.2.2',
  '@openzeppelin/ui-types': '3.0.0',
  '@openzeppelin/ui-components': '3.0.0',
  '@openzeppelin/ui-utils': '3.0.0',
  '@openzeppelin/ui-styles': '1.1.0',
};
