/**
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT IT MANUALLY.
 *
 * To update these versions, run the script:
 * pnpm update-export-versions
 */

export const packageVersions = {
  '@openzeppelin/adapter-evm': '1.1.0',
  '@openzeppelin/adapter-midnight': '1.1.0',
  '@openzeppelin/adapter-polkadot': '1.1.0',
  '@openzeppelin/adapter-solana': '1.1.0',
  '@openzeppelin/adapter-stellar': '1.1.0',
  '@openzeppelin/ui-react': '2.0.0',
  '@openzeppelin/ui-renderer': '2.0.0',
  '@openzeppelin/ui-storage': '1.2.1',
  '@openzeppelin/ui-types': '2.0.0',
  '@openzeppelin/ui-components': '2.0.0',
  '@openzeppelin/ui-utils': '2.0.0',
  '@openzeppelin/ui-styles': '1.0.0',
};
