/**
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT IT MANUALLY.
 *
 * To update these versions, run the script:
 * pnpm update-export-versions
 */

export const packageVersions = {
  '@openzeppelin/adapter-evm': '3.0.0',
  '@openzeppelin/adapter-midnight': '2.2.0',
  '@openzeppelin/adapter-polkadot': '3.0.0',
  '@openzeppelin/adapter-solana': '2.2.0',
  '@openzeppelin/adapter-stellar': '3.0.0',
  '@openzeppelin/ui-react': '3.3.1',
  '@openzeppelin/ui-renderer': '3.4.1',
  '@openzeppelin/ui-storage': '1.2.4',
  '@openzeppelin/ui-types': '3.5.1',
  '@openzeppelin/ui-components': '3.8.2',
  '@openzeppelin/ui-utils': '4.0.0',
  '@openzeppelin/ui-styles': '1.1.0',
};
