---
name: Pre-requisites
description: |
  Setup Pre-requisites

inputs:
  token:
    required: true
  fetch-depth:
    description: Number of commits to fetch (0 for full history)
    required: false
    default: '1'

runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        token: ${{ inputs.token }}
        persist-credentials: true
        fetch-depth: ${{ inputs.fetch-depth }}

    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        run_install: false

    - name: Use node@22
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 22.18.0
        cache: 'pnpm'

    - name: Install dependencies
      run: |
        pnpm install-deps
      shell: bash
