import React from 'react';

import { Label, RadioField } from '@openzeppelin/transaction-form-renderer';

import type { PrimaryMethodSelectorProps } from '../types';

export function PrimaryMethodSelector({
  control,
  adapterAvailable,
  options,
}: PrimaryMethodSelectorProps): React.ReactElement {
  return (
    <div className="space-y-4 rounded-md border p-4 md:p-6">
      <Label className="text-base font-medium">Execution Method</Label>
      <p className="text-muted-foreground text-sm">
        Select how transactions generated by this form should be executed.
      </p>
      {adapterAvailable ? (
        <div className="pt-2">
          <RadioField
            id="execution-method-type-selector"
            label="Primary Execution Method Selection" // Hidden label/fieldset legend
            name="executionMethodType"
            control={control}
            options={options}
          />
        </div>
      ) : (
        <p className="text-muted-foreground text-sm">No blockchain adapter selected.</p>
      )}
    </div>
  );
}

PrimaryMethodSelector.displayName = 'PrimaryMethodSelector';
